---
- name: Pre-Flight Validation
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check connectivity
      ping:

    - name: Check disk space
      shell: df -h / | awk 'NR==2 {print $4}'
      register: disk_space

    - name: Verify sufficient disk space
      assert:
        that: 
          - disk_space.stdout | regex_replace('G.*', '') | int > 2
        fail_msg: "Insufficient disk space: {{ disk_space.stdout }}"

    - name: Check memory
      shell: free -m | awk 'NR==2{printf "%.1f", $7/1024}'
      register: available_memory

    - name: Verify sufficient memory
      assert:
        that:
          - available_memory.stdout | float > 1.0
        fail_msg: "Insufficient memory: {{ available_memory.stdout }}GB available"

    - name: Display validation results
      debug:
        msg: |
          Host: {{ inventory_hostname }}
          Disk Space: {{ disk_space.stdout }}
          Available Memory: {{ available_memory.stdout }}GB
          OS Family: {{ ansible_os_family }}
          Ready for deployment: {{ 'YES' if (disk_space.stdout | regex_replace('G.*', '') | int > 5) and (available_memory.stdout | float > 1.0) else 'NO' }}