---
- name: Pre-Flight Validation
  hosts: all
  gather_facts: yes
  tasks:
    - name: Check connectivity
      ping:

    - name: Check disk space
      shell: df -h / | awk 'NR==2 {print $4}'
      register: disk_space

    - name: Verify sufficient disk space
      assert:
        that: 
          - disk_space.stdout | regex_replace('G.*', '') | int > 5
        fail_msg: "Insufficient disk space: {{ disk_space.stdout }}"

    - name: Check memory
      shell: free -m | awk 'NR==2{printf "%.1f", $7/1024}'
      register: available_memory

    - name: Verify sufficient memory
      assert:
        that:
          - available_memory.stdout | float > 1.0
        fail_msg: "Insufficient memory: {{ available_memory.stdout }}GB available"

    - name: Test external CI/CD connectivity
      uri:
        url: "http://{{ jenkins_host }}:8080"
        method: GET
        status_code: [200, 403]
      delegate_to: localhost
      ignore_errors: yes
      register: jenkins_check

    - name: Display validation results
      debug:
        msg: |
          Disk Space: {{ disk_space.stdout }}
          Available Memory: {{ available_memory.stdout }}GB
          Jenkins Connectivity: {{ 'OK' if jenkins_check.status == 200 or jenkins_check.status == 403 else 'FAILED' }}