---
- name: Install Java 21 (Ubuntu)
  apt:
    name: openjdk-17-jdk
    state: present
  when: ansible_os_family == "Debian"
  tags: nexus

- name: Add Eclipse Temurin repository (Rocky Linux)
  yum_repository:
    name: adoptium
    description: Eclipse Temurin
    baseurl: https://packages.adoptium.net/artifactory/rpm/rhel/9/x86_64
    gpgkey: https://packages.adoptium.net/artifactory/api/gpg/key/public
    gpgcheck: yes
  when: ansible_os_family == "RedHat"
  tags: nexus

- name: Install Java 17 (Rocky Linux)
  dnf:
    name: temurin-17-jdk
    state: present
  when: ansible_os_family == "RedHat"
  tags: nexus

- name: Create nexus user
  user:
    name: nexus
    system: yes
    shell: /bin/bash
    home: /opt/nexus
  tags: nexus

- name: Copy Nexus tar file
  copy:
    src: nexus-3.70.1-02-unix.tar.gz
    dest: /tmp/nexus.tar.gz
  tags: nexus

- name: Check if Nexus is already extracted
  stat:
    path: /opt/nexus-3.83.0-08
  register: nexus_extracted
  tags: nexus

- name: Extract Nexus
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: /opt
    remote_src: yes
    owner: nexus
    group: nexus
    creates: /opt/nexus-3.83.0-08
  when: not nexus_extracted.stat.exists
  tags: nexus

- name: Find extracted Nexus application directory
  find:
    paths: /opt
    patterns: "nexus-3.*"
    file_type: directory
  register: nexus_app_dir
  tags: nexus

- name: Remove existing nexus symlink
  file:
    path: /opt/nexus
    state: absent
  tags: nexus

- name: Create symlink to Nexus application
  file:
    src: "{{ nexus_app_dir.files[0].path }}"
    dest: /opt/nexus
    state: link
  when: nexus_app_dir.files|length > 0
  tags: nexus

- name: Configure Nexus service
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
  notify: restart nexus
  tags: nexus

- name: Configure firewall for Nexus (Ubuntu)
  ufw:
    rule: allow
    port: "8081"
  when: ansible_os_family == "Debian"
  tags: nexus

- name: Configure firewall for Nexus (Rocky Linux)
  firewalld:
    port: 8081/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
  tags: nexus

- name: Start Nexus service
  systemd:
    name: nexus
    state: started
    enabled: yes
    daemon_reload: yes
  tags: nexus