---
- name: Install Java 8
  apt:
    name: openjdk-8-jdk
    state: present

- name: Create nexus user
  user:
    name: nexus
    system: yes
    shell: /bin/bash
    home: /opt/nexus

- name: Download Nexus
  get_url:
    url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
    dest: /tmp/nexus.tar.gz

- name: Extract Nexus
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: /opt
    remote_src: yes
    owner: nexus
    group: nexus

- name: Create symlink
  file:
    src: /opt/nexus-3.*
    dest: /opt/nexus
    state: link
    owner: nexus
    group: nexus

- name: Configure Nexus JVM options
  template:
    src: nexus.vmoptions.j2
    dest: /opt/nexus/bin/nexus.vmoptions
    owner: nexus
    group: nexus

- name: Configure Nexus service
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
  notify: restart nexus

- name: Configure firewall for Nexus
  ufw:
    rule: allow
    port: "8081"

- name: Start Nexus service
  systemd:
    name: nexus
    state: started
    enabled: yes
    daemon_reload: yes