---
- name: Install Java 21 (Ubuntu)
  apt:
    name: openjdk-17-jdk
    state: present
  when: ansible_os_family == "Debian"
  tags: nexus

- name: Install Java 21 (Rocky Linux)
  dnf:
    name: java-21-openjdk
    state: present
  when: ansible_os_family == "RedHat"
  tags: nexus

- name: Create nexus user
  user:
    name: nexus
    system: yes
    shell: /bin/bash
    home: /opt/nexus
  tags: nexus

- name: Copy Nexus tar file
  copy:
    src: nexus-3.83.0-08-linux-x86_64.tar.gz
    dest: /tmp/nexus.tar.gz
  tags: nexus

- name: Extract Nexus
  unarchive:
    src: /tmp/nexus.tar.gz
    dest: /opt
    remote_src: yes
    owner: nexus
    group: nexus
  tags: nexus

- name: Find extracted Nexus directory
  find:
    paths: /opt
    patterns: "nexus-*"
    file_type: directory
  register: nexus_dir
  tags: nexus

- name: Create symlink
  file:
    src: "{{ nexus_dir.files[0].path }}"
    dest: /opt/nexus
    state: link
    owner: nexus
    group: nexus
  when: nexus_dir.files|length > 0
  tags: nexus

- name: Configure Nexus service
  template:
    src: nexus.service.j2
    dest: /etc/systemd/system/nexus.service
  notify: restart nexus
  tags: nexus

- name: Configure firewall for Nexus (Ubuntu)
  ufw:
    rule: allow
    port: "8081"
  when: ansible_os_family == "Debian"
  tags: nexus

- name: Configure firewall for Nexus (Rocky Linux)
  firewalld:
    port: 8081/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
  tags: nexus

- name: Start Nexus service
  systemd:
    name: nexus
    state: started
    enabled: yes
    daemon_reload: yes
  tags: nexus