all:
  children:
    cicd:
      hosts:
        rocky-cicd:
          ansible_host: 192.168.1.157
          ansible_user: simoda
          # 16GB RAM - Rocky Linux 10 - Jenkins + Nexus + SonarQube
    app:
      hosts:
        app-server:
          ansible_host: 192.168.198.131
          ansible_user: ubuntu
          # 2GB RAM - Nginx proxy + app deployment + agents
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
