all:
  children:
    cicd:
      hosts:
        cicd-server:
          ansible_host: 192.168.198.135
          ansible_user: ubuntu
    app:
      hosts:
        app-server:
          ansible_host: 192.168.198.143
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'