all:
  children:
    jenkins:
      hosts:
        jenkins-master:
          ansible_host: 192.168.1.10
          ansible_user: ubuntu
    nexus:
      hosts:
        nexus-server:
          ansible_host: 192.168.1.11
          ansible_user: ubuntu
    sonar:
      hosts:
        sonar-server:
          ansible_host: 192.168.1.12
          ansible_user: ubuntu
    app:
      hosts:
        app-server:
          ansible_host: 192.168.1.13
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'