---
- name: Install Java 11
  apt:
    name: openjdk-11-jdk
    state: present

- name: Add Jenkins GPG key
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    state: present

- name: Add Jenkins repository
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Configure firewall for Jenkins
  ufw:
    rule: allow
    port: "8080"

- name: Start Jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to start
  wait_for:
    port: 8080
    delay: 30

- name: Get Jenkins initial password
  slurp:
    src: /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password

- name: Display Jenkins initial password
  debug:
    msg: "Jenkins initial password: {{ jenkins_password.content | b64decode }}"