---
- name: Deploy Base Infrastructure
  hosts: all
  become: yes
  roles:
    - common

- name: Setup Docker
  hosts: all
  become: yes
  roles:
    - docker

- name: Deploy App Server
  hosts: app
  become: yes
  roles:
    - nginx